export interface Job {
  id: string;
  title: string;
  company: string;
  location: string;
  salary: string;
  type: string;
  category: string[];
  companySize: string;
  isTopCompany: boolean;
  distance: number;
}

export const jobsData: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "Google",
    location: "Mountain View, CA",
    salary: "$150k - $200k",
    type: "full-time",
    category: ["tech", "top", "frontend"],
    companySize: "large",
    isTopCompany: true,
    distance: 5,
  },
  {
    id: "2",
    title: "Machine Learning Engineer",
    company: "Microsoft",
    location: "Redmond, WA",
    salary: "$160k - $220k",
    type: "full-time",
    category: ["tech", "top", "ml-ai"],
    companySize: "large",
    isTopCompany: true,
    distance: 15,
  },
  {
    id: "3",
    title: "Full Stack Developer",
    company: "Stripe",
    location: "San Francisco, CA",
    salary: "$140k - $180k",
    type: "full-time",
    category: ["tech", "top", "fullstack"],
    companySize: "large",
    isTopCompany: true,
    distance: 3,
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Amazon",
    location: "Seattle, WA",
    salary: "$145k - $195k",
    type: "full-time",
    category: ["tech", "top", "devops"],
    companySize: "large",
    isTopCompany: true,
    distance: 8,
  },
  {
    id: "5",
    title: "Backend Developer",
    company: "Netflix",
    location: "Los Gatos, CA",
    salary: "$155k - $210k",
    type: "full-time",
    category: ["tech", "top", "backend"],
    companySize: "large",
    isTopCompany: true,
    distance: 12,
  },
  {
    id: "6",
    title: "Frontend Developer",
    company: "Airbnb",
    location: "San Francisco, CA",
    salary: "$130k - $170k",
    type: "full-time",
    category: ["tech", "top", "frontend"],
    companySize: "large",
    isTopCompany: true,
    distance: 2,
  },
  {
    id: "7",
    title: "Software Engineer",
    company: "RocketTech",
    location: "Remote",
    salary: "$90k - $120k",
    type: "full-time",
    category: ["tech", "startup", "fullstack"],
    companySize: "startup",
    isTopCompany: false,
    distance: 0,
  },
  {
    id: "8",
    title: "AI Research Engineer",
    company: "DeepMind",
    location: "London, UK",
    salary: "£80k - £120k",
    type: "full-time",
    category: ["tech", "top", "ml-ai"],
    companySize: "large",
    isTopCompany: true,
    distance: 25,
  },
  {
    id: "9",
    title: "React Native Developer",
    company: "InnovateApp",
    location: "Austin, TX",
    salary: "$100k - $130k",
    type: "full-time",
    category: ["tech", "startup", "mobile"],
    companySize: "startup",
    isTopCompany: false,
    distance: 18,
  },
  {
    id: "10",
    title: "Cloud Architect",
    company: "Salesforce",
    location: "San Francisco, CA",
    salary: "$170k - $230k",
    type: "full-time",
    category: ["tech", "top", "devops"],
    companySize: "large",
    isTopCompany: true,
    distance: 4,
  },
  {
    id: "11",
    title: "Data Engineer",
    company: "Snowflake",
    location: "San Mateo, CA",
    salary: "$140k - $190k",
    type: "full-time",
    category: ["tech", "top", "data"],
    companySize: "large",
    isTopCompany: true,
    distance: 7,
  },
  {
    id: "12",
    title: "Product Designer",
    company: "Figma",
    location: "San Francisco, CA",
    salary: "$130k - $170k",
    type: "full-time",
    category: ["design", "top"],
    companySize: "large",
    isTopCompany: true,
    distance: 3,
  },
  {
    id: "13",
    title: "iOS Developer",
    company: "MobileFirst",
    location: "Remote",
    salary: "$95k - $125k",
    type: "contract",
    category: ["tech", "startup", "mobile"],
    companySize: "startup",
    isTopCompany: false,
    distance: 0,
  },
  {
    id: "14",
    title: "Security Engineer",
    company: "CyberGuard",
    location: "Boston, MA",
    salary: "$130k - $180k",
    type: "full-time",
    category: ["tech", "security"],
    companySize: "medium",
    isTopCompany: false,
    distance: 22,
  },
  {
    id: "15",
    title: "Technical Lead",
    company: "Square",
    location: "San Francisco, CA",
    salary: "$180k - $240k",
    type: "full-time",
    category: ["tech", "top", "leadership"],
    companySize: "large",
    isTopCompany: true,
    distance: 1,
  },
  {
    id: "16",
    title: "QA Engineer",
    company: "TestPro",
    location: "Remote",
    salary: "$85k - $110k",
    type: "full-time",
    category: ["tech", "qa"],
    companySize: "medium",
    isTopCompany: false,
    distance: 0,
  },
  {
    id: "17",
    title: "Blockchain Developer",
    company: "CryptoFuture",
    location: "Miami, FL",
    salary: "$140k - $190k",
    type: "full-time",
    category: ["tech", "startup", "blockchain"],
    companySize: "startup",
    isTopCompany: false,
    distance: 30,
  },
  {
    id: "18",
    title: "UX Researcher",
    company: "DesignLab",
    location: "Seattle, WA",
    salary: "$110k - $150k",
    type: "full-time",
    category: ["design", "research"],
    companySize: "medium",
    isTopCompany: false,
    distance: 10,
  },
  {
    id: "19",
    title: "Site Reliability Engineer",
    company: "LinkedIn",
    location: "Sunnyvale, CA",
    salary: "$160k - $220k",
    type: "full-time",
    category: ["tech", "top", "devops"],
    companySize: "large",
    isTopCompany: true,
    distance: 6,
  },
  {
    id: "20",
    title: "Growth Marketing Manager",
    company: "GrowthGenius",
    location: "Remote",
    salary: "$90k - $120k",
    type: "full-time",
    category: ["marketing", "startup"],
    companySize: "startup",
    isTopCompany: false,
    distance: 0,
  },
  {
    id: "21",
    title: "Unity Game Developer",
    company: "GameStudio",
    location: "Los Angeles, CA",
    salary: "$100k - $140k",
    type: "full-time",
    category: ["tech", "gaming"],
    companySize: "medium",
    isTopCompany: false,
    distance: 15,
  },
  {
    id: "22",
    title: "Technical Product Manager",
    company: "Uber",
    location: "San Francisco, CA",
    salary: "$170k - $220k",
    type: "full-time",
    category: ["tech", "top", "product"],
    companySize: "large",
    isTopCompany: true,
    distance: 2,
  },
  {
    id: "23",
    title: "Data Scientist",
    company: "AISolutions",
    location: "New York, NY",
    salary: "$130k - $180k",
    type: "full-time",
    category: ["tech", "startup", "data"],
    companySize: "startup",
    isTopCompany: false,
    distance: 28,
  },
  {
    id: "24",
    title: "Systems Administrator",
    company: "TechOps",
    location: "Chicago, IL",
    salary: "$85k - $120k",
    type: "full-time",
    category: ["tech", "infrastructure"],
    companySize: "medium",
    isTopCompany: false,
    distance: 12,
  },
  {
    id: "25",
    title: "AR/VR Developer",
    company: "MetaVerse",
    location: "Remote",
    salary: "$120k - $160k",
    type: "contract",
    category: ["tech", "startup", "ar-vr"],
    companySize: "startup",
    isTopCompany: false,
    distance: 0,
  },
];
